name: js-ci Pipeline #name of workflow
 
on: [push] #events that trigger the workflow

jobs: 
  test:
    runs-on: ubuntu-lastest
    steps:
      -name: Checkout code
       uses: actions/checkout@v4
      -name: Setup Node.js
       uses: actions/setup-node@v4
       with:
        node-version: '22.14'
      -name: Install dependencies
       run: npm install
      -name: Run tests
       run: npm test
